name: vetri_indane_worker_app
description: "Vetri Indane Driver & Loadman Mobile Application (RDK Technologies)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  http: ^1.2.1
  geolocator: ^11.0.0
  qr_flutter: ^4.1.0
  intl: ^0.19.0
  pdf: ^3.10.8
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
